spring.application.name=elite-Motors
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/elite_motors
spring.datasource.username=postgres
spring.datasource.password=admin123

# Hibernate Properties (Auto create tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect