# 1. Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/elitemotors_db
spring.datasource.username=postgres
spring.datasource.password=1234
# (Uda "your_password" kiyana thanata oyage postgres password eka danna)

# 2. JPA / Hibernate Settings
# Database eka update wenna oni widiya (update dunnama tables auto hadenawa)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# 3. Server Port (Frontend eka 5173 nisa api meka 8080 thiyamu)
server.port=8080